name: CD Publish to npm

on:
  workflow_dispatch:

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm install --omit=optional
        working-directory: ./sdk/javascript
      - run: npm run build
        working-directory: ./sdk/javascript
      - run: npm publish --access=public
        working-directory: ./sdk/javascript
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
